### ISSUE TITLE
Support for CSAI / Multiple ad breaks

### ISSUE THREAD

**Issue by slowmove** [Eyevinn/test-adserver#52]
- [x] Possible to send in _insertion points_, in seconds, comma separated (e.g. `insertionpoints=0,300,723`
- [x] Possible to get response as VMAP

**Comment by birme** [comment]
Propose this is implemented with a new endpoint `/api/v1/vmap` that is similar to the `/api/v1/vast` endpoint but returns a VMAP instead and can take a list of insertion points as specified.
