### ISSUE TITLE
Running on Heroku

### ISSUE THREAD

**Issue by wabiloo** [Eyevinn/test-adserver#67]
Hi,
I've been trying to get this app to run on Heroku, but so far without success.

I added a Procfile containing simply
```web: node server.js```
I also committed the `package-lock.json` (as per https://devcenter.heroku.com/articles/getting-started-with-nodejs#declare-app-dependencies)

But that's not sufficient.

The heroku app logs contain:
```at=error code=H10 desc="App crashed" method=GET path="/api/v1/vast?dur=120"```

Any vague idea?  (I'm not super-familar with node apps running in Heroku)
Running it locally (whether with `npm start` or `heroku local:start`) works fine

**Comment by birme** [comment]
What version of node are you running on heroku?

**Comment by wabiloo** [comment]
I managed to get around the error by moving the `"fast-xml-parser": "^3.21.1"` dependency from `devDependencies` to `dependencies` in the `package.json` (and therefore overwriting the `"fast-xml-parser": "^3.20.0"` that was in there)

**Comment by birme** [comment]
Ok, would you mind contributing with a PR with the fix?

**Comment by birme** [comment]
And thanks!

**Comment by wabiloo** [comment]
https://github.com/Eyevinn/test-adserver/pull/68
