### ISSUE TITLE
Weird default domain name `[::1]`

### ISSUE THREAD

**Issue by wabiloo** [Eyevinn/test-adserver#69]
Hi,

More of a question than a bug. And I assume this is a fastify thing rather than the ad server.
Still, I'm asking here in case you have an idea. I couldn't find anything with some research in the fastify docs.

```Test Adserver API is listening at http://[::1]:8080```

When I start the ad server (with `npm start`) locally on my Mac, the domain name seems to default to `[::1]`, instead of `localhost` or `127.0.0.1`. I have an environment variable `HOST` that is set (by standard) to `MyMachineName.local`.

Any idea?
I can start with `HOST=127.0.0.1 npm start` but that seems odd...

**Comment by birme** [comment]
That tells fastify on which IP to bind the listening port to. I can agree that the environment variable HOST might be misleading but it is absolutely correct as you do if you want to bind it to 127.0.0.1 interface.
If HOST is not set it will default to 0.0.0.0 which is basically ANY interface.

**Comment by birme** [comment]
Let me know if this didn't answer your question.

**Comment by wabiloo** [comment]
That it binds to 0.0.0.0 I understand, but why `[::1]`?  
And why is it not taking my system-wide environment variable `HOST` which is set to `MyMachineName.local`?

**Comment by birme** [comment]
HOST is in this case an interface IP. Default 0.0.0.0 should work in your case and required if it is run in a container

**Comment by birme** [comment]
And ::1 is the ipv6 loopback address

**Comment by birme** [comment]
The env variable you might want to set is ADSERVER to be your host name
